version: '3.4'

services:
  priceservice:
    image: ${DOCKER_REGISTRY-}priceservice
    build:
      context: .
      dockerfile: PriceService/Dockerfile

  bookingservice:
    image: ${DOCKER_REGISTRY-}bookingservice
    build:
      context: .
      dockerfile: BookingService/Dockerfile

