CREATE TABLE IF NOT EXISTS maxcar.Car (
  Id INT NOT NULL AUTO_INCREMENT,
  Code VARCHAR(45) NOT NULL,
  Price DECIMAL(18,2) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX Id_UNIQUE (Id ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS maxcar.Booking (
  Id INT NOT NULL AUTO_INCREMENT,
  `Start` DATETIME NOT NULL,
  `End` DATETIME NOT NULL,
  CarId INT NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX Id_UNIQUE (Id ASC) VISIBLE,
  CONSTRAINT CarId_Car
    FOREIGN KEY (Id)
    REFERENCES maxcar.Car (Id)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION);

INSERT INTO maxcar.Car(Id,Code,Price)
VALUES 
   (1, 'Mercedes', 50),
   (2, 'BMW',  60),
   (3, 'Nissan', 20);